From 4c1f1371e98c387cb07043c26b99beff5b5111a8 Mon Sep 17 00:00:00 2001
From: Alan Wright <alan@spotify.com>
Date: Mon, 28 Apr 2014 13:53:48 +0100
Subject: [PATCH] Throw exception in fixture destructor instead of FAIL().

---
 src/test/util/LuceneTestFixture.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/test/util/LuceneTestFixture.cpp b/src/test/util/LuceneTestFixture.cpp
index 27c61e0..e737bdb 100644
--- a/src/test/util/LuceneTestFixture.cpp
+++ b/src/test/util/LuceneTestFixture.cpp
@@ -21,7 +21,7 @@ LuceneTestFixture::~LuceneTestFixture() {
     if (ConcurrentMergeScheduler::anyUnhandledExceptions()) {
         // Clear the failure so that we don't just keep failing subsequent test cases
         ConcurrentMergeScheduler::clearUnhandledExceptions();
-        FAIL() << "ConcurrentMergeScheduler hit unhandled exceptions";
+        boost::throw_exception(RuntimeException(L"ConcurrentMergeScheduler hit unhandled exceptions"));
     }
 }
 
